stages:
  - build
  - deploy

before_script: 
  - docker login registry.gitag.ir -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
build:
  stage: build
  script:
    - docker build -t registry.gitag.ir/ctp_vault .
    - docker push registry.gitag.ir/ctp_vault

deploy-prod:
  stage: deploy
  only: 
    - master
  needs:
    - build
  script:
    - cp $ENV_PROD .env
    - docker-compose up -d --force-recreate
